version: "3"
services:
  frontend:
    build: ./
    volumes:
      - /node_modules
    ports:
      - 3000:3000
    container_name: ip_front
    depends_on:
      - flyway

  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:mysql://db -schemas=Iptable -user=root -password=Aa12345!! -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    container_name: mvw_flyway
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Aa12345!!
    ports:
      - 3305:3305
    container_name: mvw_db
